CLUSTERS = ['K-means','WARD','Spectral','DBSCAN','BANG','SOM','Fuzzy C-Means']
MONTH = '6'
YEAR = '18'
PLAYERBASE_SIZE = '17000'
N_CLUSTER = 3
QUERYSTORM = 'SELECT id,name,race,gender,free_company,realm,grand_company,legacy_player,level_lancer,level_pugilist,level_rogue,level_archer,level_machinist,level_darkknight,level_gladiator,level_marauder,level_thaumaturge,level_conjurer,level_astrologian,level_arcanist,level_blacksmith,level_weaver,level_leatherworker,level_carpenter,level_goldsmith,level_culinarian,level_armorer,level_alchemist,level_fisher,level_botanist,level_miner,p30days,p60days,p90days,p180days,p270days,p360days,p450days,p630days,p960days,hildibrand,prearr,prehw,beforemeteor,beforethefall,hwartbookone,hwartbooktwo,topazcarubuncleplush,soundtrack,moogleplush,hasencyclopedia,emeraldcarbuncleplush,arrartbook,amaljaa,sylph,vanuvanu,vath,sahagin,moogle,kobold,dideternalbond,saweternalbond,level_samurai,level_redmage FROM ffxivcensus.tblplayers'+MONTH+YEAR+' ORDER BY RAND() LIMIT '+PLAYERBASE_SIZE
NULL_QUERY = "SELECT COUNT(*) FROM ffxivcensus.tblplayers"+MONTH+YEAR+" WHERE name = null OR race = null OR gender = null OR free_company = null OR realm = null OR grand_company = null OR legacy_player = null OR level_alchemist = null OR level_arcanist = null OR level_archer = null OR level_armorer = null OR level_astrologian = null OR level_blacksmith = null OR level_botanist = null OR level_carpenter = null OR level_conjurer = null OR level_culinarian = null OR level_darkknight = null OR level_fisher = null OR level_gladiator = null OR level_goldsmith = null OR level_lancer = null OR level_leatherworker = null OR level_machinist = null OR level_marauder = null OR level_miner = null OR level_pugilist = null OR level_rogue = null OR level_thaumaturge = null OR level_weaver = null OR p180days = null OR p270days = null OR p30days = null OR p360days = null OR p450days = null OR p60days = null OR p630days = null OR p90days = null OR p960days = null OR hildibrand = null OR prearr = null OR prehw = null OR beforemeteor = null OR beforethefall = null OR hwartbookone = null OR hwartbooktwo = null OR topazcarubuncleplush = null OR soundtrack = null OR moogleplush = null OR hasencyclopedia = null OR emeraldcarbuncleplush = null OR arrartbook = null OR amaljaa = null OR sylph = null OR vanuvanu = null OR vath = null OR sahagin = null OR moogle = null OR kobold = null OR dideternalbond = null OR saweternalbond = null"
NULL_QUERY_STORM = "SELECT COUNT(*) FROM ffxivcensus.tblplayers"+MONTH+YEAR+" WHERE name = null OR race = null OR gender = null OR free_company = null OR realm = null OR grand_company = null OR legacy_player = null OR level_alchemist = null OR level_arcanist = null OR level_archer = null OR level_armorer = null OR level_astrologian = null OR level_blacksmith = null OR level_botanist = null OR level_carpenter = null OR level_conjurer = null OR level_culinarian = null OR level_darkknight = null OR level_fisher = null OR level_gladiator = null OR level_goldsmith = null OR level_lancer = null OR level_leatherworker = null OR level_machinist = null OR level_marauder = null OR level_miner = null OR level_pugilist = null OR level_rogue = null OR level_thaumaturge = null OR level_weaver = null OR p180days = null OR p270days = null OR p30days = null OR p360days = null OR p450days = null OR p60days = null OR p630days = null OR p90days = null OR p960days = null OR hildibrand = null OR prearr = null OR prehw = null OR beforemeteor = null OR beforethefall = null OR hwartbookone = null OR hwartbooktwo = null OR topazcarubuncleplush = null OR soundtrack = null OR moogleplush = null OR hasencyclopedia = null OR level_samurai = null OR level_redmage = null OR emeraldcarbuncleplush = null OR arrartbook = null OR amaljaa = null OR sylph = null OR vanuvanu = null OR vath = null OR sahagin = null OR moogle = null OR kobold = null OR dideternalbond = null OR saweternalbond = null"

NUMBER_ATRIBUTES = 21
NUMBER_HIGH_CORRELATED_ATRIBUTES = 14
NAME_COLUMNS = ["race","gender","freeCompany","realm","grand_company","legacy_player","physicalMeeleExp","physicalRangeExp","tankExp","magicRangeExp","healerExp","arcanistExp","craftExp","gatherExp","minimalCPTime","hildibrand","PreArr", "PreHw", "PObject", "Marriage", "BTCompleted"]
HIGH_CORRELATED_COLUMNS = ["free_company","physicalMeeleExp","physicalRangeExp","tankExp","magicRangeExp","healerExp","arcanistExp","craftExp","gatherExp","minimalCertainPaidTime","preHw","hildibrand",  "marriage", "beastTribesCompleted"]
RESUMED_COLUMNS = ['FCom','PMExp','PRExp','TExp','MRExp','HExp','ArcExp','CrExp','GaExp','mmCPTime','Hldn','PreHw','Mrrg','BTC']